version: '3.8'

services:
  mongo_container:
    image: ismaildaniyal/mongodb:latest
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork

  node_container:
    build: .
    image: ismaildaniyal/node_app:latest
    container_name: node_container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo_container
    networks:
      - mynetwork
    environment:
      MONGO_URI: mongodb://mongo_container:27017/mydatabase

volumes:
  mongo_data:

networks:
  mynetwork:
    driver: bridge