name: Docker Build and Push  # Defines the name of the workflow

on:
  push:
    branches:
      - main

jobs:
  buildnpush:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


      - name: Build the Docker Image
        run: docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/node_app:latest" .

      - name: Tag the Image
        run: docker tag "${{ secrets.DOCKERHUB_USERNAME }}/node_app:latest" "${{ secrets.DOCKERHUB_USERNAME }}/node_app:latest"

      - name: Push the Image
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/node_app:latest"